apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-container-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-serving
  template:
    metadata:
      labels:
        app: model-serving
    spec:
      containers:
      - name: model-serving-container
        image: model:v001
        resources:
          limits:
            memory: "1024Mi"
            cpu: "0.5"
        ports:
        - containerPort: 8500

